version: '3.4'

services:

   reactapp:
    ports:
      - "3000:3000"

   sqlserver:
     environment :
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12*
     volumes:
       - sqlserver_volume:/var/opt/mssql
     ports:
      - "1433:1433"
   courseapp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
      - "5001:443"


