version: '3.4'

services:
   reactapp:
    build:
      context: ./src/ClientApp
      dockerfile: Dockerfile
   courseapp.api:
    image: courseappapi-image
    container_name: courseapi-container
    build:
      context: .
      dockerfile: src/Presentation/CourseApp.API/Dockerfile 
   sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
   redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

volumes:
  sqlserver_volume :